-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 13:37:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema practica4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema practica4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practica4` DEFAULT CHARACTER SET utf8 ;
USE `practica4` ;

-- -----------------------------------------------------
-- Table `practica4`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica4`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `imagen` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `practica4`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica4`.`inventario` (
  `idinventario` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `idproducto` INT(11) NOT NULL,
  PRIMARY KEY (`idinventario`),
  INDEX `fk_inventario_producto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `practica4`.`producto` (`idproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
