package com.everis.equipo3practica4.model;
// Generated 3/10/2019 10:31:07 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PedidoHasProducto generated by hbm2java
 */
@Entity
@Table(name = "pedido_has_producto", catalog = "practica4")
public class PedidoHasProducto implements java.io.Serializable {

	private Integer id;
	private Pedido pedido;
	private Producto producto;

	public PedidoHasProducto() {
	}

	public PedidoHasProducto(Pedido pedido, Producto producto) {
		this.pedido = pedido;
		this.producto = producto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pedido_idpedido", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto_idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

}
