package com.everis.equipo3practica4.model;
// Generated 3/10/2019 11:54:22 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Producto generated by hbm2java
 */
/////
@Entity
@Table(name = "producto", catalog = "practica4")
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private String descripcion;
	private String nombre;
	private double precio;
	private String imagen;
	@JsonIgnore
	private Set<Inventario> inventarios = new HashSet<Inventario>(0);

	public Producto() {
	}

	public Producto(String descripcion, String nombre, double precio, String imagen) {
		this.descripcion = descripcion;
		this.nombre = nombre;
		this.precio = precio;
		this.imagen = imagen;
	}

	public Producto(String descripcion, String nombre, double precio, String imagen, Set<Inventario> inventarios) {
		this.descripcion = descripcion;
		this.nombre = nombre;
		this.precio = precio;
		this.imagen = imagen;
		this.inventarios = inventarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproducto", unique = true, nullable = false)
	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "imagen", nullable = false, length = 200)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "producto")
	public Set<Inventario> getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set<Inventario> inventarios) {
		this.inventarios = inventarios;
	}

}
